### PR TITLE
Added cron task

### PR DESCRIPTION
**Pull request by wachterjohannes**

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@alexander-schranz daily tasks now running each day on midnight do you think thats a problem?

**Comment by alexander-schranz** [comment]
When is the first run of a new this task then? Think it should be immediatily?

**Comment by wachterjohannes** [comment]
the first run is on 24:00 on the same day. if you want a special date you can specify it with the cron-expression.

**Comment by alexander-schranz** [comment]
In my use cases it should be immediatily. This could be done by set the daily task on today 00:00 instead of the next day.

**Pull request merged**
